import SiteNav from "@/components/SiteNav";
import SiteFooter from "@/components/SiteFooter";

export const metadata = {
  title: "Affiliate Disclosure — BuildMyOutfit",
  description:
    "Affiliate Disclosure for BuildMyOutfit.com — how we earn commissions from qualifying purchases at no extra cost to you.",
};

const LAST_UPDATED = "March 2026";

export default function AffiliateDisclosurePage() {
  return (
    <div
      className="min-h-screen bg-white"
      style={{ fontFamily: "Arial, Helvetica, sans-serif" }}
    >
      <SiteNav />

      {/* Page Header */}
      <section className="bg-black text-white py-16 sm:py-24">
        <div className="max-w-4xl mx-auto px-5">
          <p className="text-xs font-bold tracking-widest text-gray-500 uppercase mb-4">
            Legal
          </p>
          <h1 className="text-4xl sm:text-6xl font-black tracking-tight leading-none mb-5">
            Affiliate Disclosure
          </h1>
          <p className="text-gray-400 text-lg leading-relaxed max-w-2xl">
            Last updated: {LAST_UPDATED}
          </p>
        </div>
      </section>

      {/* Content */}
      <main className="max-w-3xl mx-auto px-5 py-16 sm:py-20">
        <div className="space-y-12">

          {/* Summary callout */}
          <div className="bg-gray-50 border border-gray-200 rounded-2xl p-6 sm:p-8">
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-3">
              The short version
            </p>
            <p className="text-lg font-semibold text-gray-900 leading-relaxed">
              Some links on BuildMyOutfit go to retailers like Amazon. If you
              buy something through one of those links, we may earn a small
              commission —{" "}
              <span className="underline decoration-2 underline-offset-2">
                at no extra cost to you
              </span>
              . You pay the same price either way.
            </p>
          </div>

          <Section title="How we make money">
            <p className="text-gray-600 leading-relaxed mb-3">
              BuildMyOutfit is free to use. To keep it that way, we partner
              with retailers through affiliate programs. When you click a
              product link and make a purchase, the retailer pays us a small
              referral fee.
            </p>
            <p className="text-gray-600 leading-relaxed">
              Think of it like a finder's fee — the store thanks us for sending
              you their way. You don't pay anything extra, and your price is
              never marked up.
            </p>
          </Section>

          <Section title="Who we work with">
            <p className="text-gray-600 leading-relaxed mb-4">
              Right now, most of our product links go through:
            </p>
            <div className="bg-gray-50 rounded-xl p-5 mb-6">
              <p className="text-sm font-bold text-gray-900 mb-1">
                Amazon Associates Program
              </p>
              <p className="text-sm text-gray-500 leading-relaxed">
                We link to products on Amazon.com. If you buy within 24 hours
                of clicking our link, we earn a percentage of the sale.
                Amazon sets the price — we have no influence over what you pay.
              </p>
            </div>
            <p className="text-gray-600 leading-relaxed">
              We may partner with other retailers down the road. If we do,
              we'll update this page.
            </p>
          </Section>

          <Section title="Does this affect what we recommend?">
            <p className="text-gray-600 leading-relaxed mb-3">
              No. Our recommendations are generated by color-matching logic
              based on your photo — not by commission rates or brand deals.
            </p>
            <p className="text-gray-600 leading-relaxed">
              A $30 item that genuinely matches your colors will always beat a
              $200 item that doesn't. That's the whole point of the tool.
            </p>
          </Section>

          <Section title="How to spot affiliate links">
            <p className="text-gray-600 leading-relaxed">
              Product buttons labeled "View on Amazon" or "Shop Now" are
              affiliate links. They take you directly to the product page —
              the only difference is a tracking tag in the URL so the retailer
              knows we referred you.
            </p>
          </Section>

          <Section title="FTC disclosure">
            <p className="text-gray-600 leading-relaxed">
              We're required by the FTC to tell you about our affiliate
              relationships, and we're happy to. This page, our site footer,
              and product pages all carry this disclosure. We believe in being
              upfront — you should always know how a site makes money.
            </p>
          </Section>

          <Section title="Still have questions?">
            <p className="text-gray-600 leading-relaxed">
              Reach out anytime at{" "}
              <a
                href="mailto:support@buildmyoutfit.com"
                className="text-gray-900 underline hover:text-gray-600"
              >
                support@buildmyoutfit.com
              </a>
              . We're happy to explain how any of this works.
            </p>
          </Section>

        </div>
      </main>

      <SiteFooter />
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section>
      <h2 className="text-xl font-black text-gray-900 mb-4">{title}</h2>
      {children}
    </section>
  );
}
